global:
  scrape_interval: 15s

remote_write:
  - url: "http://prometheus:9090/api/v1/write"  # prometheus 자신이 remote_write를 받는 척함 (k6용)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']